### ISSUE TITLE
please make a ZENODO archive for the version used in the Nature News coverage

### ISSUE THREAD

**Issue by egonw** [pkerpedjiev/gene-citation-counts#2]
Nice to see your work here on GitHub! For public record, please consider making a ZENODO archive (or somewhere else) of your script. GitHub has an easy to use integration to make it happen.

Because I think it would be great to have the Nature feature linked to the actual code in a more permanent way than a volatile source code repository.

https://www.nature.com/articles/d41586-017-07291-9

**Comment by pkerpedjiev** [comment]
To be honest, I didn't realize that they would link to the code repository.  I just created a release and am waiting for Zenodo to recognize it and issue it a DOI.

Thanks for the suggestion!

**Comment by egonw** [comment]
Oh, and you can add the DOI with a nice, simple badge to your readme markdown, e.g. see https://github.com/bridgedb/BridgeDb

**Comment by pkerpedjiev** [comment]
Done!
