### ISSUE TITLE
Trying to run updated in python 2 and 3

### ISSUE THREAD

**Issue by ryandikdan** [pkerpedjiev/gene-citation-counts#6]
Hello, I can't seem to get the first script to work. I might not have all the modules installed, but I tried to pip them. I have 3 and 2 installed and when I run default (3) this is what I get:
```
python pmids_by_date
.py --startdate 1990/01/01 --enddate 2020/07/13;
Traceback (most recent call last):
  File "pmids_by_date.py", line 55, in <module>
    main()
  File "pmids_by_date.py", line 49, in main
    with open(output_file, 'w') as fout:
FileNotFoundError: [Errno 2] No such file or directory: './data/pmid_by_date/1990_01_02.ssv'
```
When I try to run python 2 this is what I get:
```
python2.7 pmids_by_d
ate.py --startdate 1990/01/01 --enddate 2020/07/13;
Traceback (most recent call last):
  File "pmids_by_date.py", line 7, in <module>
    import urllib.request as ur
ImportError: No module named request
```

I'm really just trying to get an up to date list of genes. I used pip to install datetime, but the others seemed okay. I have urllib3, and I tried to change the name in the file, but it didn't work. 
Upon looking some stuff up I think it might have to do with changes to urllib.request.urlopen since I don't see that command as much in the new stuff. Thanks.

**Comment by ryandikdan** [comment]
While trying to figure this out, I found this website from ncbi that has all these stats. While it is a bit of a pain to format, it's a bit easier than trying to get this script up and running. Good luck anyone else in the future! ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/

**Comment by pkerpedjiev** [comment]
Hey, glad you found the data at NCBI and thanks for posting the link. This repo is a bit of a relic and I don't have the willpower to maintain it. Sorry you spent time to trying to get it to work. I'll add a section to the README discouraging others from doing the same.
